// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjvoiyjpyjagfrxtispo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdm9peWpweWphZ2ZyeHRpc3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjE0NTcsImV4cCI6MjA3MjEzNzQ1N30.9eWugE3yXiqnZINFeZPBllBujaHVYkPWJrpNr4TQPZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});